"""empty message

Revision ID: 20bb3931c63c
Revises: fa57efe847ec
Create Date: 2017-05-27 23:17:22.251472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bb3931c63c'
down_revision = 'fa57efe847ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('skill', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'skill')
    # ### end Alembic commands ###
