"""empty message

Revision ID: fa57efe847ec
Revises: 
Create Date: 2017-05-22 22:36:05.253606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa57efe847ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_job', sa.String(length=255), nullable=True),
    sa.Column('name_business', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=144), nullable=True),
    sa.Column('email', sa.String(length=144), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('modality', sa.String(length=10), nullable=True),
    sa.Column('employment_contract', sa.String(length=40), nullable=True),
    sa.Column('salary', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('date_pub', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('date_apply', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('fk_job', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_job'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicant')
    op.drop_table('job')
    # ### end Alembic commands ###
